### ISSUE TITLE
modular-magician still creating PRs in ansible/ansible

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/ansible_collections_google#180]
Hi,
Should modular-magician be creating PRs in this repo now, rather than in ansible/ansible?

Could modular-magician please be disabled for ansible/ansible

https://github.com/ansible/ansible/labels/gce

**Comment by rambleraptor** [comment]
Sorry about the noise! We turned off the pipeline yesterday, so no further PRs should be made towards ansible/ansible. I'll go through the past PRs and close them out.

**Comment by gundalow** [comment]
Thanks Alex :)
